name: JukeBox
author: SkytAsul
version: 1
description: A plugin which allows you to propose note block songs to your players.
main: fr.skytasul.music.JukeBox
api-version: 1.21
website: https://www.spigotmc.org/resources/jukebox-music-plugin.40580/
depend: [NoteBlockAPI]
softdepend: [PlaceholderAPI]
commands:
  music:
    description: Main command for musics
    aliases: [jukebox]
    permission: music.command
